services:

 xolo-db:
  image: mongo:8-noble
  ports:
    - ${XOLO_MONGODB_PORT-27018}:27017
  volumes:
    - xolo-db:/data/db
    - ./db/mongod.conf:/etc/mongo/mongod.conf:ro
  networks:
    - xolo-net
  restart: unless-stopped
  command: ["mongod", "--config","/etc/mongo/mongod.conf"]


 xolo-cache:
  image: redis:7.0.11-alpine
  ports:
    - 6379:6379
  volumes:
    - xolo-cache-data:/data
  networks:
    - xolo-net
  restart: unless-stopped
  # command: ["redis-server", "--appendonly", "yes"]
  # command: ["redis-server", "--appendonly", "yes", "--requirepass", "d22a75e9e729debc"]
  # environment:
    # - REDIS_PASSWORD=d22a75e9e729debc
  # Uncomment the above lines to enable Redis authentication
  # Make sure to update the application code to use the password when connecting to Redis
  # For security reasons, avoid hardcoding passwords in production environments
 xolo:
  build:
    context: .
    dockerfile: ${XOLO_DOCKERFILE-./Dockerfile}
  image: ${XOLO_IMAGE-xolo:api-0.0.11a0}
  container_name: xolo-api
  env_file:
    - .env.dev
  ports:
    - ${XOLO_PORT-10000}:${XOLO_PORT-10000}
  volumes:
    # - /log:/log
    - xolo-data:/xolo
  networks:
    - xolo-net
  restart: unless-stopped
  depends_on:
    - xolo-db
  command: uvicorn xoloapi.server:app --host ${XOLO_HOST-0.0.0.0} --port ${XOLO_PORT-10000} ${XOLO_RELOAD+--reload} --log-level debug

networks:
 xolo-net:
  external: true
volumes:
 xolo-db:
  external: true
 xolo-cache-data:
 xolo-data:
  # external: true