import datetime
from typing import Protocol, Tuple

from option import Option, Result
from commonx.dto.xolo import CreateUserDTO
from commonx.models.xolo import User
import commonx.errors as EX

from xoloapi.users.domain.aggregates import PasswordResetToken


class IUsersRepository(Protocol):
    async def enable_user(self, account_id: str, username: str) -> Result[bool, EX.XError]: ...
    async def disable_user(self, account_id: str, username: str) -> Result[bool, EX.XError]: ...
    async def set_access_token(self, account_id: str, username: str, access_token: str, temp_secret_key: str, exp: str = "15min") -> Result[bool, EX.XError]: ...
    async def get_access_token(self, account_id: str, username: str) -> Result[Option[Tuple[str, str]], EX.XError]: ...
    async def delete_access_token(self, account_id: str, username: str) -> Result[bool, EX.XError]: ...
    async def update_password(self, account_id: str, username: str, password: str) -> Result[bool, EX.XError]: ...
    async def create(self, account_id: str, user: CreateUserDTO) -> Result[str, EX.XError]: ...
    async def find_by_id(self, user_id: str, account_id: str | None = None) -> Option[User]: ...
    async def find_by_email(self, account_id: str, email: str) -> Option[User]: ...
    async def find_by_username(self, account_id: str, username: str) -> Option[User]: ...
    async def find_all(self, account_id: str) -> Result[list[User], EX.XError]: ...
    async def delete_by_id(self, user_id: str, account_id: str | None = None) -> Result[bool, EX.XError]: ...


class IPasswordResetRepository(Protocol):
    async def create(self, token: PasswordResetToken) -> Result[PasswordResetToken, EX.XError]: ...
    async def find_active_by_hash(self, token_hash: str) -> Result[Option[PasswordResetToken], EX.XError]: ...
    async def invalidate_for_user(self, account_id: str, user_id: str, used_at: datetime.datetime | None = None) -> Result[bool, EX.XError]: ...
    async def mark_used(self, request_id: str, used_at: datetime.datetime | None = None) -> Result[bool, EX.XError]: ...
