from typing import Protocol

from option import Result
import commonx.errors as EX
import commonx.models.xolo as MX

from xoloapi.scopes.dto import AssignScopeDTO, CreateScopeDTO


class IScopesRepository(Protocol):
    async def exists_scope_user(self, account_id: str, name: str, username: str) -> Result[bool, EX.XError]: ...
    async def count_scope_users(self, account_id: str, name: str) -> Result[int, EX.XError]: ...
    async def exists_scope(self, account_id: str, name: str) -> Result[bool, EX.XError]: ...
    async def find_scope_by_name(self, account_id: str, name: str) -> Result[MX.ScopeModel, EX.XError]: ...
    async def create(self, account_id: str, dto: CreateScopeDTO) -> Result[str, EX.XError]: ...
    async def delete(self, account_id: str, name: str) -> Result[bool, EX.XError]: ...
    async def assign(self, account_id: str, dto: AssignScopeDTO) -> Result[str, EX.XError]: ...
    async def unassign(self, account_id: str, dto: AssignScopeDTO) -> Result[bool, EX.XError]: ...
    async def find_all_scopes(self, account_id: str) -> Result[list[MX.ScopeModel], EX.XError]: ...
    async def find_all_scope_users(self, account_id: str) -> Result[list[MX.ScopeUserModel], EX.XError]: ...
    async def delete_assignments_for_username(self, account_id: str, username: str) -> Result[int, EX.XError]: ...
