from typing import Protocol

import commonx.errors as EX
from option import Result


class ILicensesRepository(Protocol):
    async def create(self, account_id: str, username: str, license: str, scope: str, expires_at: str) -> Result[bool, EX.XError]: ...
    async def find_by_username_and_scope(self, account_id: str, username: str, scope: str) -> Result[str, EX.XError]: ...
    async def delete_by_username_scope(self, account_id: str, username: str, scope: str) -> Result[bool, EX.XError]: ...
    async def count_by_scope(self, account_id: str, scope: str) -> Result[int, EX.XError]: ...
    async def find_all(self, account_id: str) -> Result[list, EX.XError]: ...
    async def delete_all_by_username(self, account_id: str, username: str) -> Result[int, EX.XError]: ...
